# libradtran-interface configure

DEBUG=0
FLAG_UNDISPLAY_LOG=1
DIR_LOG=/home/sano/sano1/temporary1/2libr1/
FLAG_SINGLESHOT=1

# DIRECTORY
DIR_INTERFACE=/home/sano/sano1/research1/estimate-profile1/2libradtran-interface/libradtran-interface/
DIR_UVSPEC=/home/sano/sano1/research1/LIBRARIES1/libradtran/2libradtran/libRadtran-2.0.6/bin/
DIR_RESULT=/home/sano/sano1/research1/estimate-profile1/2026/2026-09w1/const_b/shot_std0.5e-2/07/2021-04-29/2210/
DIR_OBS=/home/sano/sano1/data1/himawaridata/
PATH_STDIN=/home/sano/sano1/temporary1/2libr1/in
PATH_STDOUT=/home/sano/sano1/temporary1/2libr1/out
PATH_ATMOSPHERE=/home/sano/sano1/temporary1/2libr1/atm.dat
MOLECULES_FILE=/home/sano/sano1/research1/estimate-profile1/afglus_101_log.dat
FLAG_USE_ATMOSPHERE_INIT=0
PATH_ATMOSPHERE_INIT=/home/sano/sano1/research1/estimate-profile1/2026/2026-09w1/const_b/msis/07/2021-04-29/2210/msis_2021-04-29_2210_07.dat

# GENERAL
#wavelength=470
PATH_WAVELENGTHS=/home/sano/sano1/research1/estimate-profile1/ObsEquip/Spectrum/470.dat
HIMAWARI_BAND=1
SZA_THRESHOLD=90.0
i_top=70
i_bottom=15
#SINGLESHOT
#fit_i_top=
#fit_i_bottom=
#
N_exp_decay_atm=5
PATH_OBS_BACKGROUND_INTENSITY=/home/sano/sano1/research1/estimate-profile1/2026/2026-09w1/b_0.dat

# LibRadtran
solver=mystic
additional_option=aerosol_default\nmc_vroom on\nmc_std 0.5e-2\nverbose\nmol_abs_param crs\n
SURFACE_TYPE=ABSORB
#albedo=0.9
mc_basename=mc2libr1
# brdf_cam_u10=5

# MYSTIC
mc_photons=100000000

# ATMOSPHERE
atmosphere_precision=7

OPTIMIZER=NL

#NLopt
XTOL_REL=1.0e-6

#fit


FITTING_ADDITION=0


FLAG_OTEHON=0
#PATH_OTEHON=/lhome/sano2/SANO/research/estimate-profile/Result/02-W2/MSIS/result_20190101_075000_25__id1771041732_0.dat
#OTEHON_LAT=
#OTEHON_LON=

# MEMO
# 最適化中の高度範囲以下も最適化中のスケールハイトになるように変更(やりすぎる数密度が増えすぎて大気内の計算が終わらなくなるため、（マイナスの）下限を設定)
